
version: '3.8'

services:
  frontend:
    image: omkarm7/frontendfinal:v1
    ports:
      - 5005:80
  

  APIGatewayService:
    image: omkarm7/apigateway:v1
    ports:
     - "7115:80"

  UserMervice:
    image: omkarm7/userservice:v1
    ports:
     - "7124:80"

  ProductService:
    image: omkarm7/productservice:v1
    ports:
     - "7033:80"
  




